[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  framework = "#custom"
  command = "npm run dev:parcel"
  targetPort = 1234
  port = 8080
  publish = "dist"
  autoLaunch = false
